site_configs: &site_configs
  navbar_brand_html: >
    <a href="/" class="navbar-brand"><b>青创</b> 综合组</a>
  navbar_html: >
    <li><a href="/topics/new">发帖</a>
  wiki_index_html: >
    <div>Wiki Home page.</div>
  wiki_sidebar_html: >
    <strong>推荐内容</strong>
    <ul>
      <li><a href="/wiki/about">关于我们</a></li>
    </ul>
  footer_html: >
    <p class="copyright">
     &copy; Powered by <a href="http://gethomeland.com">Homeland</a>.
    </p>
  after_topic_html: ""
  before_topic_html: ""
  topic_index_sidebar_html: ""
  site_index_html: "下面列出了相关网站。如果你知道还有不在此列表的，请帮忙补充。"
  custom_head_html: >
    <link rel="dns-prefetch" href="//assets.your-host.com">
  node_ids_hide_in_topics_index: ""
  new_topic_dropdown_node_ids: ""
  ban_words_on_reply: >
    mark
    收藏
    顶
    赞
    up
  tips: >
    提示1
    提示2
  newbie_notices: >
    <p>已经移除发帖时间限制，新用户可以立即发帖。</p>
  reject_newbie_reply_in_the_evening: false
  apns_pem: ""
  blacklist_ips: ""

defaults: &defaults
  <<: *site_configs
  app_name: "青创·综合组论坛"
  modules: "<%= ENV['modules'] %>"
  domain: "<%= ENV['domain'] %>"
  https: <%= ENV['https'] || 'true' %>
  admin_emails: <%= ENV['admin_emails'] %>
  google_analytics_key: "<%= ENV['google_analytics_key'] %>"
  asset_host: "<%= ENV['asset_host'] %>"
  <% if ENV['rack_attack.limit'] == 'true' %>
  rack_attack:
    limit: <%= ENV['rack_attack.limit'] %>
    period: <%= ENV['rack_attack.period'] %>
  <% end %>
  upload_provider: "<%= ENV['upload_provider'] %>" # can be  upyun/aliyun
  upload_access_id: "<%= ENV['upload_access_id'] %>" # or username
  upload_access_secret: "<%= ENV['upload_access_secret'] %>" # or upyun password
  upload_bucket: "<%= ENV['upload_bucket'] %>"
  upload_url: "<%= ENV['upload_url'] %>"
  upload_aliyun_internal: <%= ENV['upload_aliyun_internal'] == 'true' %>
  upload_aliyun_area: "<%= ENV['upload_aliyun_area'] %>"
  mailer_provider: "<%= ENV['mailer_provider'] %>"
  mailer_sender: "<%= ENV['mailer_sender'] %>"
  mailer_options:
    <% if ENV['mailer_provider'] == 'postmark' %>
    api_key: '<%= ENV['mailer_options.api_key'] %>'
    <% else %>
    address: '<%= ENV['mailer_options.address'] %>'
    port: <%= ENV['mailer_options.port'] %>
    domain: '<%= ENV['mailer_options.domain'] %>'
    user_name: '<%= ENV['mailer_options.user_name'] %>'
    password: '<%= ENV['mailer_options.password'] %>'
    authentication: '<%= ENV['mailer_options.authentication'] %>'
    enable_starttls_auto: <%= ENV['mailer_options.enable_starttls_auto'] %>
    <% end %>
  github_token: "<%= ENV['github_token'] %>"
  github_secret: "<%= ENV['github_secret'] %>"

production:
  <<: *defaults
